export const residentialAreas = [
  "Airport Area",
  "College Park",
  "East Point",
  "Hapeville",
  "Atlanta",
  "South Fulton",
  "Union City",
  "Fairburn",
  "Palmetto",
  "Forest Park",
  "Riverdale",
  "Jonesboro",
  "Morrow",
  "Lovejoy",
  "Fayetteville",
  "Peachtree City",
  "McDonough",
  "Stockbridge",
  "Hampton",
  "Newnan",
  "Douglasville",
  "Decatur / DeKalb County",
  "Other Metro Atlanta",
];

export const residentialAreaGroups = [
  "Airport Area — College Park, East Point, Hapeville",
  "South Fulton — Union City, Fairburn, Palmetto",
  "Clayton County — Forest Park, Riverdale, Jonesboro, Morrow, Lovejoy",
  "Fayette County — Fayetteville, Peachtree City",
  "Henry County — McDonough, Stockbridge, Hampton",
  "Coweta County — Newnan and surrounding area",
  "Douglas County — Douglasville",
  "Atlanta",
  "DeKalb County / Decatur",
  "Other Metro Atlanta",
];
