import { useMemo, useState } from "react";
import "./Childcare.css";

const seed=[
{id:"c1",name:"Early Start Childcare",type:"Childcare Provider",area:"College Park",hours:"4:30 AM–8:00 PM",schedule:["Early morning","Day"],ages:"6 weeks–12 years",rate:"From $185/week",verified:false,icon:"🌅",description:"Extended weekday hours designed for parents who need care before traditional centers open. Airport-area location with early drop-off."},
{id:"c2",name:"Airport Parent — Childcare Swap",type:"Care Exchange",area:"East Point",hours:"Schedule varies",schedule:["Evening","Weekend"],ages:"School age",rate:"Exchange / discuss",verified:false,icon:"🤝",description:"Community childcare exchange concept for airport employees with opposite or complementary schedules. Connect first and make your own care arrangements."},
{id:"c3",name:"24-Hour Family Care",type:"Childcare Provider",area:"Hapeville",hours:"24-hour availability",schedule:["Early morning","Overnight","Weekend"],ages:"Infant–10 years",rate:"Contact provider",verified:false,icon:"🌙",description:"Prototype listing demonstrating overnight and nontraditional-hour care close to the airport employment area."},
{id:"c4",name:"Weekend Sitter Available",type:"Individual Caregiver",area:"South Fulton",hours:"Sat–Sun, flexible",schedule:["Weekend","Day","Evening"],ages:"Toddler–12 years",rate:"$18/hr",verified:false,icon:"🧸",description:"Weekend availability for families working airport schedules. This is a demonstration profile, not a verified caregiver."},
{id:"c5",name:"After-School Pickup & Care",type:"Individual Caregiver",area:"College Park",hours:"2:00 PM–10:00 PM",schedule:["Evening"],ages:"School age",rate:"$20/hr",verified:false,icon:"🎒",description:"Example after-school care listing for employees whose shifts extend into the evening."},
{id:"c6",name:"Looking for Overnight Care",type:"Care Needed",area:"Airport Area",hours:"9:00 PM–7:00 AM",schedule:["Overnight"],ages:"4 years",rate:"Budget $150/week",verified:false,icon:"🔎",description:"Airport employee seeking dependable overnight childcare several nights each week. General area only until contact is established."}
];
const schedules=["All schedules","Early morning","Day","Evening","Overnight","Weekend"];
const types=["All options","Childcare Provider","Individual Caregiver","Care Exchange","Care Needed"];
const areas=["All areas","College Park","East Point","Hapeville","South Fulton","Airport Area","Forest Park","Riverdale","Union City"];
function readMine(){try{return JSON.parse(localStorage.getItem("airportChildcareListings")||"[]")}catch{return[]}}

export default function Childcare(){
 const [mine,setMine]=useState(readMine),[q,setQ]=useState(""),[schedule,setSchedule]=useState("All schedules"),[type,setType]=useState("All options"),[posting,setPosting]=useState(false),[selected,setSelected]=useState(null);
 const listings=useMemo(()=>[...mine,...seed].filter(x=>{const s=q.trim().toLowerCase();return(type==="All options"||x.type===type)&&(schedule==="All schedules"||x.schedule.includes(schedule))&&(!s||[x.name,x.area,x.hours,x.ages,x.description].join(" ").toLowerCase().includes(s))}),[mine,q,type,schedule]);
 function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);const x={id:"mine-"+Date.now(),name:f.get("name"),type:f.get("type"),area:f.get("area"),hours:f.get("hours"),schedule:[f.get("schedule")],ages:f.get("ages"),rate:f.get("rate"),verified:false,icon:f.get("type")==="Care Needed"?"🔎":"🧸",description:f.get("description")};const n=[x,...mine];localStorage.setItem("airportChildcareListings",JSON.stringify(n));setMine(n);setPosting(false);setSelected(x)}
 function remove(id){const n=mine.filter(x=>x.id!==id);localStorage.setItem("airportChildcareListings",JSON.stringify(n));setMine(n);setSelected(null)}
 if(posting)return <main className="page childcare-page"><button className="childcare-back" onClick={()=>setPosting(false)}>← Back to Childcare</button><form className="childcare-form" onSubmit={submit}><span className="eyebrow">CHILDCARE COMMUNITY</span><h1>Post childcare or a care need.</h1><p>Designed for the schedules that make airport work difficult to fit into traditional childcare hours.</p><div className="childcare-two"><label>Listing type<select name="type">{types.filter(x=>x!=="All options").map(x=><option key={x}>{x}</option>)}</select></label><label>Name / listing title<input name="name" required placeholder="Weekend sitter available" /></label></div><div className="childcare-two"><label>General area<select name="area">{areas.filter(x=>x!=="All areas").map(x=><option key={x}>{x}</option>)}</select></label><label>Primary schedule need<select name="schedule">{schedules.filter(x=>x!=="All schedules").map(x=><option key={x}>{x}</option>)}</select></label></div><div className="childcare-two"><label>Hours / availability<input name="hours" required placeholder="4:30 AM–2:00 PM" /></label><label>Ages served / child age<input name="ages" required placeholder="Infant–10 years" /></label></div><label>Rate / budget<input name="rate" required placeholder="$18/hr, $185/week, or discuss" /></label><label>Description<textarea name="description" rows="6" required maxLength="900" /></label><div className="childcare-warning"><strong>Safety first</strong><span>Do not post a child's full name, school, exact home address, badge number or other sensitive information.</span></div><button className="continue-button">Publish Childcare Listing →</button></form></main>;
 if(selected)return <main className="page childcare-page"><button className="childcare-back" onClick={()=>setSelected(null)}>← Back to Childcare</button><section className="childcare-detail"><div className="childcare-icon-large">{selected.icon}</div><div><span className="childcare-type">{selected.type}</span><h1>{selected.name}</h1><strong className="childcare-rate">{selected.rate}</strong><p>{selected.description}</p><div className="childcare-facts"><span>📍 {selected.area}</span><span>🕒 {selected.hours}</span><span>👶 {selected.ages}</span><span>📆 {selected.schedule.join(" · ")}</span></div><div className="childcare-verification"><strong>{selected.verified?"✓ Verification information available":"⚠ Not verified by Airport Community"}</strong><p>Families should independently review licensing where applicable, references, background-check information and suitability before arranging care.</p></div>{selected.id.startsWith("mine-")?<button className="secondary-button" onClick={()=>remove(selected.id)}>Remove Listing</button>:<button className="continue-button" onClick={()=>alert("Childcare contact will use the shared community messaging component.")}>Message / Ask About Care →</button>}</div></section></main>;
 return <main className="page childcare-page"><section className="childcare-hero"><div><span className="eyebrow">CHILDCARE</span><h1>Childcare that understands airport hours.</h1><p>Explore care around early starts, late finishes, overnight shifts and weekends—not just a 9-to-5 schedule.</p></div><button className="primary-button" onClick={()=>setPosting(true)}>＋ Post Childcare</button></section><section className="shift-strip"><div><strong>🌅 Early AM</strong><span>Before traditional centers open</span></div><div><strong>🌆 Evening</strong><span>Care beyond standard pickup</span></div><div><strong>🌙 Overnight</strong><span>For cross-midnight shifts</span></div><div><strong>📅 Weekend</strong><span>Saturday & Sunday coverage</span></div></section><div className="childcare-search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search childcare, hours, ages or area…" /><select value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select><select value={schedule} onChange={e=>setSchedule(e.target.value)}>{schedules.map(x=><option key={x}>{x}</option>)}</select></div><div className="childcare-grid">{listings.map(x=><button className="childcare-card" key={x.id} onClick={()=>setSelected(x)}><div className="childcare-icon">{x.icon}</div><div><span className="childcare-type">{x.type}</span><h2>{x.name}</h2><strong>{x.rate}</strong><p>📍 {x.area} · 🕒 {x.hours}</p><div className="childcare-tags">{x.schedule.map(s=><span key={s}>{s}</span>)}</div></div></button>)}</div><div className="childcare-footer"><strong>A community connection tool—not a childcare agency.</strong><span>Provider licensing and trust/verification features will be developed before live public use.</span></div></main>
}