import { useMemo, useState } from "react";
import "./CommunityResources.css";

const resources=[
{id:"r1",title:"MARTA Airport Station",category:"Transportation",icon:"🚆",summary:"Rail connection directly into ATL plus bus connections throughout the region.",detail:"Use this resource to explore public-transit connections for getting to and from airport work. Future versions can connect directly to the commute planner."},
{id:"r2",title:"Georgia Commute Options",category:"Transportation",icon:"🚐",summary:"Regional commute resources including carpool and vanpool programs.",detail:"A useful starting point for employees interested in recurring shared transportation and commute alternatives."},
{id:"r3",title:"Airport Employee Emergency Ride Help",category:"Transportation",icon:"🆘",summary:"Community information for unexpected gaps in an employee's normal ride home.",detail:"This will connect with the transportation module as the emergency and final-mile features mature."},
{id:"r4",title:"Food Assistance & Community Pantries",category:"Financial & Family",icon:"🥫",summary:"Find food-assistance programs and community pantry resources near the airport workforce.",detail:"Future live resources can be organized by county and proximity to major airport-worker residential areas."},
{id:"r5",title:"Childcare Assistance Resources",category:"Financial & Family",icon:"👶",summary:"Programs that may help families locate or afford childcare.",detail:"Designed to complement the Childcare module, especially for employees working nontraditional schedules."},
{id:"r6",title:"Utility & Rental Assistance",category:"Financial & Family",icon:"🏠",summary:"A starting point for community programs offering housing, rental or utility support.",detail:"Resources can later be localized by county and updated with eligibility and application links."},
{id:"r7",title:"Workforce Training & Career Resources",category:"Career",icon:"🎓",summary:"Training, certification and career-development opportunities for airport-area workers.",detail:"This section can connect employees with workforce-development programs and complement Jobs / Now Hiring."},
{id:"r8",title:"Resume & Job Search Help",category:"Career",icon:"📄",summary:"Resources for resumes, interviews and finding the next airport-area opportunity.",detail:"Future versions can link directly to verified workforce partners and airport hiring events."},
{id:"r9",title:"Mental Health & Crisis Resources",category:"Health & Wellness",icon:"💚",summary:"A directory area for confidential mental-health, crisis and wellness support.",detail:"Live deployment should prioritize authoritative providers and clearly identify emergency versus non-emergency resources."},
{id:"r10",title:"Low-Cost Health & Community Clinics",category:"Health & Wellness",icon:"🏥",summary:"Find community health resources around the airport workforce region.",detail:"Future listings can include eligibility, hours, languages and general service areas."},
{id:"r11",title:"Legal Aid & Consumer Help",category:"Practical Help",icon:"⚖️",summary:"Community legal-aid and consumer-support resources.",detail:"This directory can point employees toward authoritative nonprofit and government assistance without attempting to replace professional advice."},
{id:"r12",title:"211 Community Services",category:"Practical Help",icon:"☎️",summary:"A broad starting point for local social-service and community-support needs.",detail:"Useful when an employee knows they need help but does not yet know which specific program to contact."}
];
const categories=["All Resources","Transportation","Financial & Family","Career","Health & Wellness","Practical Help"];

export default function CommunityResources(){
 const [q,setQ]=useState(""),[cat,setCat]=useState("All Resources"),[selected,setSelected]=useState(null);
 const filtered=useMemo(()=>resources.filter(r=>{const s=q.trim().toLowerCase();return(cat==="All Resources"||r.category===cat)&&(!s||[r.title,r.category,r.summary,r.detail].join(" ").toLowerCase().includes(s))}),[q,cat]);
 if(selected)return <main className="page resources-page"><button className="resources-back" onClick={()=>setSelected(null)}>← Back to Resources</button><section className="resource-detail"><div className="resource-icon-large">{selected.icon}</div><div><span className="resource-category">{selected.category}</span><h1>{selected.title}</h1><p>{selected.summary}</p><div className="resource-detail-note">{selected.detail}</div><button className="continue-button" onClick={()=>alert("Verified live links and contact information will be connected during the resource-data phase.")}>View Resource Information →</button></div></section></main>;
 return <main className="page resources-page"><section className="resources-hero"><div><span className="eyebrow">COMMUNITY RESOURCES</span><h1>One place to find practical help.</h1><p>Transportation, family support, career resources, wellness and other useful services for the airport community.</p></div></section><div className="resources-search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="What do you need help with?" /></div><div className="resource-categories">{categories.map(c=><button key={c} className={cat===c?"active":""} onClick={()=>setCat(c)}>{c}</button>)}</div><section className="resource-grid">{filtered.map(r=><button className="resource-card" key={r.id} onClick={()=>setSelected(r)}><div className="resource-icon">{r.icon}</div><div><span className="resource-category">{r.category}</span><h2>{r.title}</h2><p>{r.summary}</p><span className="resource-open">Explore resource →</span></div></button>)}</section><section className="resource-suggest"><div><strong>Know a resource airport employees should see here?</strong><span>Community suggestions and partner submissions can be added once moderation and verification are connected.</span></div><button onClick={()=>alert("Resource suggestions will be connected to the shared submission workflow.")}>Suggest a Resource</button></section><div className="resource-disclaimer"><strong>Resource directory</strong><span>Airport Community does not endorse or guarantee third-party services. Live links will be verified before public launch, with official or authoritative sources preferred.</span></div></main>
}