import { useMemo, useState } from "react";
import "./Housing.css";

const seed=[
{id:"h1",title:"Room for rent near College Park",price:750,type:"Room for Rent",area:"College Park",commute:"10–15 min to ATL",available:"Available now",icon:"🛏️",poster:"Airport employee",description:"Private furnished room in a shared home. Utilities included. Convenient to Airport Station and the Domestic Terminal."},
{id:"h2",title:"1-bedroom apartment in Hapeville",price:1150,type:"Apartment",area:"Hapeville",commute:"10 min to ATL",available:"Oct 1",icon:"🏢",poster:"Property listing",description:"One-bedroom apartment close to downtown Hapeville with easy access to the airport employment area."},
{id:"h3",title:"Looking for airport-worker roommate",price:650,type:"Roommate Wanted",area:"East Point",commute:"10–15 min to ATL",available:"Flexible",icon:"🤝",poster:"Airport employee",description:"Seeking a reliable roommate who understands nontraditional airport work schedules. Private bedroom in a two-bedroom unit."},
{id:"h4",title:"Studio near MARTA",price:975,type:"Apartment",area:"College Park",commute:"Rail access to ATL",available:"Available now",icon:"🚆",poster:"Property listing",description:"Compact studio within walking distance of MARTA. Useful for employees who prefer a transit commute."},
{id:"h5",title:"Room in quiet home",price:700,type:"Room for Rent",area:"Union City",commute:"15–20 min to ATL",available:"Oct 15",icon:"🏠",poster:"Community member",description:"Private room with shared kitchen and living space. Parking available. Airport workers welcome."},
{id:"h6",title:"Need a room near the airport",price:800,type:"Housing Wanted",area:"Airport Area",commute:"Prefer under 20 min",available:"By Nov 1",icon:"🔎",poster:"Airport employee",description:"Full-time airport employee looking for a room or roommate arrangement with a manageable commute to ATL."}
];
const types=["All housing","Room for Rent","Apartment","Roommate Wanted","Housing Wanted"];
const areas=["All areas","College Park","Hapeville","East Point","Union City","Airport Area","Forest Park","Riverdale","South Fulton"];
function readMine(){try{return JSON.parse(localStorage.getItem("airportHousingListings")||"[]")}catch{return[]}}

export default function Housing(){
 const [mine,setMine]=useState(readMine),[q,setQ]=useState(""),[type,setType]=useState("All housing"),[area,setArea]=useState("All areas"),[posting,setPosting]=useState(false),[selected,setSelected]=useState(null);
 const listings=useMemo(()=>[...mine,...seed].filter(x=>{const s=q.trim().toLowerCase();return(type==="All housing"||x.type===type)&&(area==="All areas"||x.area===area)&&(!s||[x.title,x.area,x.type,x.description].join(" ").toLowerCase().includes(s))}),[mine,q,type,area]);
 function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);const x={id:"mine-"+Date.now(),title:f.get("title"),price:Number(f.get("price")||0),type:f.get("type"),area:f.get("area"),commute:f.get("commute"),available:f.get("available"),icon:"🏡",poster:"My listing",description:f.get("description")};const n=[x,...mine];localStorage.setItem("airportHousingListings",JSON.stringify(n));setMine(n);setPosting(false);setSelected(x)}
 function remove(id){const n=mine.filter(x=>x.id!==id);localStorage.setItem("airportHousingListings",JSON.stringify(n));setMine(n);setSelected(null)}
 if(posting)return <main className="page housing-page"><button className="housing-back" onClick={()=>setPosting(false)}>← Back to Housing</button><form className="housing-form" onSubmit={submit}><span className="eyebrow">POST HOUSING</span><h1>Create a housing listing.</h1><p>Share the general area and useful commute information without publishing an exact home address.</p><label>Listing title<input name="title" required placeholder="Room for rent near College Park" /></label><div className="housing-two"><label>Type<select name="type">{types.filter(x=>x!=="All housing").map(x=><option key={x}>{x}</option>)}</select></label><label>Monthly price / budget<input name="price" type="number" min="0" required placeholder="750" /></label></div><div className="housing-two"><label>General area<select name="area">{areas.filter(x=>x!=="All areas").map(x=><option key={x}>{x}</option>)}</select></label><label>Availability<input name="available" required placeholder="Available now / Oct 1" /></label></div><label>Airport commute note<input name="commute" required placeholder="10–15 min to ATL / near MARTA" /></label><label>Description<textarea name="description" rows="6" required maxLength="900" placeholder="Describe the space or housing need. Do not include an exact street address." /></label><div className="housing-safety"><strong>🔒 Protect your home location.</strong><span>Post only a general area. Share an exact address only later, privately, when appropriate.</span></div><button className="continue-button">Publish Housing Listing →</button></form></main>;
 if(selected)return <main className="page housing-page"><button className="housing-back" onClick={()=>setSelected(null)}>← Back to Housing</button><section className="housing-detail"><div className="housing-photo">{selected.icon}</div><div><span className="housing-type">{selected.type}</span><h1>{selected.title}</h1><strong className="housing-price">${selected.price}/mo</strong><p>{selected.description}</p><div className="housing-facts"><span>📍 {selected.area}</span><span>✈️ {selected.commute}</span><span>📅 {selected.available}</span><span>👤 {selected.poster}</span></div><div className="housing-note"><strong>Location privacy</strong><p>Only the general area is shown. Use in-platform messaging before deciding whether to exchange more specific location information.</p></div>{selected.id.startsWith("mine-")?<button className="secondary-button" onClick={()=>remove(selected.id)}>Remove Listing</button>:<button className="continue-button" onClick={()=>alert("Housing messaging will use the shared community chat component.")}>Message About Housing →</button>}</div></section></main>;
 return <main className="page housing-page"><section className="housing-hero"><div><span className="eyebrow">HOUSING & RENTALS</span><h1>Live closer. Find a roommate. Simplify the airport commute.</h1><p>Housing and roommate opportunities organized for people who work around ATL.</p></div><button className="primary-button" onClick={()=>setPosting(true)}>＋ Post Housing</button></section><div className="housing-search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search rooms, apartments, roommates or areas…" /><select value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select><select value={area} onChange={e=>setArea(e.target.value)}>{areas.map(x=><option key={x}>{x}</option>)}</select></div><div className="housing-grid">{listings.map(x=><button className="housing-card" key={x.id} onClick={()=>setSelected(x)}><div className="housing-card-photo">{x.icon}</div><div className="housing-card-body"><span className="housing-type">{x.type}</span><h2>{x.title}</h2><strong className="housing-card-price">${x.price}/mo</strong><div className="housing-card-meta"><span>📍 {x.area}</span><span>✈️ {x.commute}</span><span>📅 {x.available}</span></div></div></button>)}</div><div className="housing-community"><strong>Built around airport life</strong><span>Future matching can connect housing searches with work location, shift schedules and transportation options without exposing private home addresses.</span></div></main>
}