import { useEffect, useMemo, useState } from "react";
import "./Jobs.css";

const seedJobs=[
{id:"j1",title:"Customer Service Agent",employer:"Airport Services Partner",area:"Domestic Terminal",type:"Full-time",shift:"Morning / Day",pay:"$17–$20/hr",badge:"Airport badge required",age:"Today",icon:"🧑‍💼",description:"Assist travelers, provide directions, support queues and deliver customer service throughout the terminal."},
{id:"j2",title:"Ramp Agent",employer:"Ground Handling Company",area:"South Cargo Area",type:"Full-time",shift:"Evening",pay:"$18–$22/hr",badge:"SIDA eligible",age:"Today",icon:"🦺",description:"Support aircraft turns, baggage movement and ramp operations in a safety-focused environment."},
{id:"j3",title:"Restaurant Team Member",employer:"Airport Concessions Operator",area:"Domestic Terminal",type:"Full-time / Part-time",shift:"Multiple shifts",pay:"$16–$19/hr",badge:"Airport badge required",age:"1d",icon:"🍽️",description:"Front- and back-of-house positions available for an airport restaurant operation."},
{id:"j4",title:"Warehouse Associate",employer:"Cargo Logistics Employer",area:"North Cargo Area",type:"Full-time",shift:"Overnight",pay:"$19–$23/hr",badge:"SIDA eligible",age:"1d",icon:"📦",description:"Receive, stage and move cargo while following airport security and safety procedures."},
{id:"j5",title:"Passenger Assistance Agent",employer:"Passenger Services Company",area:"International Terminal",type:"Part-time",shift:"Midday / Evening",pay:"$16–$18/hr",badge:"Airport badge required",age:"2d",icon:"♿",description:"Assist passengers through terminal processes and provide mobility and wayfinding support."},
{id:"j6",title:"Shuttle Driver",employer:"Airport Transportation Operator",area:"Rental Car Center",type:"Full-time",shift:"Multiple shifts",pay:"$20–$24/hr",badge:"Driver requirements apply",age:"2d",icon:"🚌",description:"Transport employees or passengers on established airport-area shuttle routes."}
];
const areas=["All areas","Domestic Terminal","International Terminal","North Cargo Area","South Cargo Area","Rental Car Center","Delta TechOps","Delta G.O."];
const types=["All types","Full-time","Part-time","Full-time / Part-time"];
function readMine(){try{return JSON.parse(localStorage.getItem("airportJobListings")||"[]")}catch{return[]}}

export default function Jobs({ session }){
 const [mine,setMine]=useState(readMine),[query,setQuery]=useState(""),[area,setArea]=useState("All areas"),[type,setType]=useState("All types"),[posting,setPosting]=useState(false),[selected,setSelected]=useState(null);
 useEffect(()=>{if(session&&sessionStorage.getItem("airportPendingAction")==="post-job"){sessionStorage.removeItem("airportPendingAction");setPosting(true)}},[session]);
 function startPosting(){if(session){setPosting(true);return}sessionStorage.setItem("airportAuthReturnTo","/jobs");sessionStorage.setItem("airportPendingAction","post-job");window.location.assign("/register")}
 const jobs=useMemo(()=>[...mine,...seedJobs].filter(j=>{const q=query.trim().toLowerCase();return(area==="All areas"||j.area===area)&&(type==="All types"||j.type.includes(type))&&(!q||[j.title,j.employer,j.area,j.shift,j.pay].join(" ").toLowerCase().includes(q))}),[mine,query,area,type]);
 function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);const j={id:"mine-"+Date.now(),title:f.get("title"),employer:f.get("employer"),area:f.get("area"),type:f.get("type"),shift:f.get("shift"),pay:f.get("pay"),badge:f.get("badge"),age:"Just now",icon:"💼",description:f.get("description")};const n=[j,...mine];localStorage.setItem("airportJobListings",JSON.stringify(n));setMine(n);setPosting(false);setSelected(j)}
 function remove(id){const n=mine.filter(x=>x.id!==id);localStorage.setItem("airportJobListings",JSON.stringify(n));setMine(n);setSelected(null)}
 if(posting)return <main className="page jobs-page"><button className="jobs-back" onClick={()=>setPosting(false)}>← Back to Jobs</button><form className="jobs-form" onSubmit={submit}><span className="eyebrow">POST AN OPPORTUNITY</span><h1>Add an airport-area job.</h1><p>Keep the posting clear about location, schedule, pay and airport access requirements.</p><label>Job title<input name="title" required /></label><label>Employer / organization<input name="employer" required /></label><div className="jobs-two"><label>Airport work area<select name="area">{areas.filter(x=>x!=="All areas").map(x=><option key={x}>{x}</option>)}</select></label><label>Employment type<select name="type"><option>Full-time</option><option>Part-time</option><option>Full-time / Part-time</option><option>Seasonal / Temporary</option></select></label></div><div className="jobs-two"><label>Typical shift<input name="shift" required placeholder="Example: 2 PM–11 PM" /></label><label>Pay range<input name="pay" required placeholder="$18–$22/hr" /></label></div><label>Badge / eligibility requirements<input name="badge" placeholder="Example: SIDA eligible" /></label><label>Job description<textarea name="description" rows="6" required /></label><button className="continue-button">Publish Job →</button></form></main>;
 if(selected)return <main className="page jobs-page"><button className="jobs-back" onClick={()=>setSelected(null)}>← Back to Jobs</button><section className="job-detail"><div className="job-detail-icon">{selected.icon}</div><div><span className="job-employer">{selected.employer}</span><h1>{selected.title}</h1><strong className="job-pay">{selected.pay}</strong><p>{selected.description}</p><div className="job-facts"><span>📍 {selected.area}</span><span>🕒 {selected.shift}</span><span>💼 {selected.type}</span><span>🪪 {selected.badge||"Ask employer"}</span></div>{selected.id.startsWith("mine-")?<button className="secondary-button" onClick={()=>remove(selected.id)}>Remove Posting</button>:<button className="continue-button" onClick={()=>alert("Application links and employer contact will be connected when live job sources are added.")}>Apply / Learn More →</button>}</div></section></main>;
 return <main className="page jobs-page"><section className="jobs-hero"><div><span className="eyebrow">JOBS / NOW HIRING</span><h1>Find opportunities across the airport community.</h1><p>Search jobs by airport work area, schedule and employment type.</p></div><button className="primary-button" onClick={startPosting}>＋ Post a Job</button></section><div className="jobs-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search job title, employer, shift or pay…" /><select value={area} onChange={e=>setArea(e.target.value)}>{areas.map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select></div><div className="jobs-count"><strong>{jobs.length} opportunities</strong><span>Prototype listings for testing</span></div><div className="jobs-list">{jobs.map(j=><button className="job-card" key={j.id} onClick={()=>setSelected(j)}><div className="job-icon">{j.icon}</div><div className="job-main"><span className="job-employer">{j.employer}</span><h2>{j.title}</h2><div className="job-tags"><span>{j.area}</span><span>{j.type}</span><span>{j.shift}</span></div></div><div className="job-card-pay"><strong>{j.pay}</strong><small>{j.age}</small></div></button>)}</div></main>
}